# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/service-v1.json
---
apiVersion: v1
kind: Service
metadata:
  name: register-placement-schools-maintenance
spec:
  selector:
    app: register-placement-schools-maintenance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
