# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/ingress-networking-v1.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: register-placement-schools-maintenance.test.teacherservices.cloud
spec:
  ingressClassName: nginx
  rules:
    - host: register-placement-schools-maintenance.test.teacherservices.cloud
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: register-placement-schools-maintenance
                port:
                  number: 80
